### ISSUE TITLE
Learn to how collaborate with Github Web GUI

### ISSUE THREAD

**Issue by ANDERSONTECHWERKS** [Josefstu/Adventure-game#3]
...And by "Web GUI": I mean the thing you are reading this on.

Anyways, simple task with this one: Reply to this issue to verify to me that you understand how to communicate via github comments. Discussions via the issues page is a pretty huge way of collaborating.

**Comment by Josefstu** [comment]
Acknowledged, closing out issue with this comment. This seems to be a very easy way to communicate issues within the codebase
